# Generated by Django 5.0 on 2026-02-25 16:20

from django.db import migrations, models


def backfill_phone_number(apps, schema_editor):
    User = apps.get_model("users", "User")
    for i, user in enumerate(User.objects.all()):
        old_phone = getattr(user, "phone", None) or ""
        if old_phone and old_phone.strip():
            user.phone_number = old_phone.strip()[:15]
        else:
            user.phone_number = f"legacy-{user.pk}"
        user.save(update_fields=["phone_number"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_optional_email_and_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, null=True, unique=False, verbose_name="phone number"),
        ),
        migrations.RunPython(backfill_phone_number, noop_reverse),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True, verbose_name="phone number"),
        ),
    ]
