# Generated by Django 5.0 on 2026-02-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_cooperatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cooperatives_cooperative',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CooperativeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cooperatives.cooperative')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cooperatives_membership',
            },
        ),
    ]
