# Generated by Django 5.0 on 2026-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemembership',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
