# Generated by Django 5.0 on 2026-02-03 15:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='cooperatives.cooperative')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'income_incomerecord',
                'ordering': ['-date', 'rider'],
            },
        ),
        migrations.AddConstraint(
            model_name='incomerecord',
            constraint=models.UniqueConstraint(fields=('rider', 'cooperative', 'date'), name='unique_income_per_rider_coop_day'),
        ),
    ]
