# Generated by Django 5.0 on 2026-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
